### PR TITLE
Add initial sun awnings support

### PR DESCRIPTION
**Pull request by Noltari**
**WORK IN PROGRESS**
This is merely a work in progress and hasn't been tested or finished.

For more info see: https://github.com/rstrouse/ESPSomfy-RTS/issues/54

### CODE REVIEW

**Comment by rstrouse** [comment]
I believe this needs to be added to the storage and persistence file for the configuration as well.   It would be great if we could narrow this down to a bitmask instead of boolean values.  You mentioned wind originally how does this flag manifest itself.  Is it always on or can the wind sensor be turned on and off.  Is that the mysterious ::Flag command that has shown up?

**Comment by Noltari** [comment]
> I believe this needs to be added to the storage and persistence file for the configuration as well. It would be great if we could narrow this down to a bitmask instead of boolean values.

I'm not familiar with the project's code, so I need some help with that, but I'll look into it.

> You mentioned wind originally how does this flag manifest itself. Is it always on or can the wind sensor be turned on and off. Is that the mysterious ::Flag command that has shown up?

Wind is always on and can't be turned off, so there are 2 possible modes: "Wind" or "Sun+Wind".
Yes, I think those modes would be ::Flag or ::SunFlag.

**Comment by rstrouse** [comment]
Ok it looks like I answered my question by RTFM at the same time you posted.
http://www.floridaautomatedshade.com/v/vspfiles/assets/catalogs/Sun%20and%20Wind%20Control/Soliris%20RTS%20Instruction%20Guide.pdf

The wind sensor cannot be disabled but the sun sensor can be turned on or off - got it.  So if you link the Soliris as if it were a linked remote it will retain the position of the awning.  If we recognize the sunflag on/off then this command can be used to link it and it will capture any up/down commands issued by the channel.

Based on what I am reading, it looks like some commands are ignored for up to 30 seconds or is this for Demo mode only.   Can this really be true?

**Comment by rstrouse** [comment]
The manual mentions an intermediate position.  Is this the My position.  If it is then this explains the my command being sent.  But I still can't wrap my head around how this is in RTS protocol not RTW.

**Comment by rstrouse** [comment]
> I'm not familiar with the project's code, so I need some help with that, but I'll look into it.

No worries I will add an options field to the output.  There is too much data to store this in any other way than LittleFS because the PHY eats up all the storage when the ESP is an Ethernet device.  If you do a backup you will see the file that is stored.  Once we figure out how all the options are stored and whether we need 1 or 2 bytes to represent it I will add it to the storage.

**Pull request merged**
