### PR TITLE
Improve Awning Sun/Wind sensor logic

### PR DESCRIPTION
**Pull request by Noltari**
If there's no sun/wind, the rolling code value will be 0, so we can't check `rollingCode > 0` for Sensor packets.

Sensor packets:
- somfy_flags_t::Windy received, the awnings should update their position to Up (as if an Up command had been issued). This doesn't depend on the SunFlag at all.
- SunFlag Enabled + somfy_flags_t::Sunny set, the awnings should update their position to Down as if a Down command had been issued.
- SunFlag Enabled + somfy_flags_t::Sunny NOT set, the awnings should update their position to Up as if an Up had been issued.

SunFlag is enabled and there's no wind:
- The awnings will go down if there's sun.
- The awnings will go up if there's no sun.

### CODE REVIEW

**Comment by Noltari** [comment]
@rstrouse I think I added all the logic described in the Soliris document [that you provided](http://www.floridaautomatedshade.com/v/vspfiles/assets/catalogs/Sun%20and%20Wind%20Control/Soliris%20RTS%20Instruction%20Guide.pdf)
image

I will test this for a couple of days and report back, and I will leave it as draft until I've confirmed it's working.

The only problem I see is the `SUN disappearing timing 15 to 30 min` but there's nothing we can do about it, so I've set it to the minimum (15 min).

**Comment by rstrouse** [comment]
I am pretty sure that the sun/wind timings are probably handled at the sensor and not the motor.  The reason I say that is because there is more than one sun sensor and it has different timings.  I suspect that we don't need to deal with any of the delays we only need to ensure we do not process any positions until we get the all-clear from the sensor.

So if a wind frame comes in that says it is not windy we can simply look to see if it is already windy by checking the flags.  If that is the case, we simply prohibit movement regardless of the commands from any remote during the timeframe.  These commands simply get tossed.

I have learned that the somfy commands do not stack or queue.  The only oddness is when we are extending the functionality to do things like seek or set and in the case of integrated tilt we maintain the tilt position after the lift movement.  So what we see are current state but never see a future state from any commanding remote.  

The motors and remotes are just not that smart.  In fact the awing motor, drapery motor, and shade motor are remarkably similar at the control head which is how you can replace an RTS control with RS485.  In every case the comms are one-way and no state is returned.

**Comment by Noltari** [comment]
> I am pretty sure that the sun/wind timings are probably handled at the sensor and not the motor. The reason I say that is because there is more than one sun sensor and it has different timings. I suspect that we don't need to deal with any of the delays we only need to ensure we do not process any positions until we get the all-clear from the sensor.

I've been monitoring my Sun/Wind sensor and so far I've only seen Sensor packets. Not a signle Up, Down, My or any other commands.

In fact, this phrase makes me think that the motor is the one handling all the logic:
`The change of setting "In" or "Out" of the Demo Mode is confirmed with a brief Jog of the motor.`
Why would the motor need to know that the Soliris is in Demo mode if the Soliris was the one sending up/down commands if windy, sunny, etc?
image

> So if a wind frame comes in that says it is not windy we can simply look to see if it is already windy by checking the flags. If that is the case, we simply prohibit movement regardless of the commands from any remote during the timeframe. These commands simply get tossed.
> 
> I have learned that the somfy commands do not stack or queue. The only oddness is when we are extending the functionality to do things like seek or set and in the case of integrated tilt we maintain the tilt position after the lift movement. So what we see are current state but never see a future state from any commanding remote.
> 
> The motors and remotes are just not that smart. In fact the awing motor, drapery motor, and shade motor are remarkably similar at the control head which is how you can replace an RTS control with RS485. In every case the comms are one-way and no state is returned.

I disagree and I think that the awning motors are smart enough to act depending on the flags received from the Sun/Wind sensors. Or at least mine do, because as I've said so far I haven't seen any position commands from my sun/wind sensor and sometimes there's a minimum delay between the motors when sun appears/disappears and not all of them start moving at the exact same time.

**Comment by rstrouse** [comment]
All the chatter around the sun sensor (Sunis) anyway, made references to up/down commands being issued.  As it turns out this is accurate for that sensor but that isn't the whole story.  That sensor sends on the 80-bit protocol so I am going to have a look and see what additional data is in the frame.

I agree that the Soliris does not operate that way and that only commands related to the state are emitted.  And the command bits are translated at the motor.  But are you sure these commands are sent and then motor then performs all the timing functions?  Or are these sent when the motor should act on them after the time delay has elapsed?  Any idea on how we might be able to confirm this?  If you look at the product evolution the Soliris appears to have come after the motors had already been developed and shipped.

I would really like to know what command they are issuing that creates the jog in demo mode but that also has me guessing whether the timing is actually controlled by the motor.  I have found that much of the original research done for decoding the protocol has been very superficial and there are two command bits on the 56-bit protocol that I have yet to see in the wild (0x0B & 0x0C).

**Comment by Noltari** [comment]
The PR is ready for review.
I've bumped the No Sun timeout delay and we may need to make these delays configurable in the future, as different manufacturers may have implemented different delays, but I think that this PR is a good start and serves as a proper base for all the awnings functionality...

> All the chatter around the sun sensor (Sunis) anyway, made references to up/down commands being issued. As it turns out this is accurate for that sensor but that isn't the whole story. That sensor sends on the 80-bit protocol so I am going to have a look and see what additional data is in the frame.
> 
> I agree that the Soliris does not operate that way and that only commands related to the state are emitted. And the command bits are translated at the motor. But are you sure these commands are sent and then motor then performs all the timing functions? Or are these sent when the motor should act on them after the time delay has elapsed? Any idea on how we might be able to confirm this? If you look at the product evolution the Soliris appears to have come after the motors had already been developed and shipped.

I'm sure that the motor is performing all the timing functions because I've seen the motors move and the last sensor commands had been issued several minutes before the movement...
Looking at the traffic issued from the Sun/Wind sensor I don't think that any bits are used for the delays and I'm pretty sure that the motors themselves are performing all the logic based on the data sent by the sensor...

> I would really like to know what command they are issuing that creates the jog in demo mode but that also has me guessing whether the timing is actually controlled by the motor. I have found that much of the original research done for decoding the protocol has been very superficial and there are two command bits on the 56-bit protocol that I have yet to see in the wild (0x0C & 0x0D).

Yes, it would be great to know. Perhaps anyone with easier access to the sensor can help us with that, because for me it's really complicated due to its location...

**Comment by rstrouse** [comment]
> I would really like to know what command they are issuing that creates the jog in demo mode but that also has me guessing whether the timing is actually controlled by the motor. I have found that much of the original research done for decoding the protocol has been very superficial and there are two command bits on the 56-bit protocol that I have yet to see in the wild (0x0C & 0x0D).
>> Yes, it would be great to know. Perhaps anyone with easier access to the sensor can help us with that, because for me it's really complicated due to its location...

Maybe we can talk @Henk72 into climbing a ladder.

I'll merge the pull.  I already have the HA component ready to go and have worked around the icon positions.  I will probably need to make some adjustments regarding the emit though.  I really do appreciate the help and hope my code wasn't too all over the place for you.

**Pull request merged**
