### PR TITLE
Add Github CI

### PR DESCRIPTION
**Pull request by Noltari**
The resulting image is untested but now LittleFS is created along with onboard.

### CODE REVIEW

**Comment by Noltari** [comment]
Ping @rstrouse

**Comment by Noltari** [comment]
Tested on LOLIN S2 Mini and it works :)

Flashing:
```
noltari@macbook-pro-alvaro ~
$ esptool.py --port /dev/cu.usbmodem01 erase_flash
esptool.py v4.5.1
Serial port /dev/cu.usbmodem01
Connecting...
Detecting chip type... Unsupported detection protocol, switching and trying again...
Detecting chip type... ESP32-S2
Chip is ESP32-S2FNR2 (revision v0.0)
Features: WiFi, Embedded Flash 4MB, Embedded PSRAM 2MB, ADC and temperature sensor calibration in BLK2 of efuse V1
Crystal is 40MHz
MAC: 84:f7:03:f4:f6:cc
Uploading stub...
Running stub...
Stub running...
Erasing flash (this may take a while)...
Chip erase completed successfully in 16.9s
WARNING: ESP32-S2FNR2 (revision v0.0) chip was placed into download mode using GPIO0.
esptool.py can not exit the download mode over USB. To run the app, reset the chip manually.
To suppress this note, set --after option to 'no_reset'.

noltari@macbook-pro-alvaro ~
$ esptool.py --port /dev/cu.usbmodem01 write_flash 0x0 Downloads/SomfyController.onboard.bin
esptool.py v4.5.1
Serial port /dev/cu.usbmodem01
Connecting...
Detecting chip type... Unsupported detection protocol, switching and trying again...
Detecting chip type... ESP32-S2
Chip is ESP32-S2FNR2 (revision v0.0)
Features: WiFi, Embedded Flash 4MB, Embedded PSRAM 2MB, ADC and temperature sensor calibration in BLK2 of efuse V1
Crystal is 40MHz
MAC: 84:f7:03:f4:f6:cc
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Flash will be erased from 0x00000000 to 0x003effff...
Compressed 4128768 bytes to 683983...
Wrote 4128768 bytes (683983 compressed) at 0x00000000 in 24.9 seconds (effective 1323.9 kbit/s)...
Hash of data verified.

Leaving...
WARNING: ESP32-S2FNR2 (revision v0.0) chip was placed into download mode using GPIO0.
esptool.py can not exit the download mode over USB. To run the app, reset the chip manually.
To suppress this note, set --after option to 'no_reset'.
```

Bootlog:
```
Connection Type: 0
NTP Settings 
pool.ntp.org TZ:
WIFI Settings
 SSID: [] PassPhrase: []
Mounting File System...
File system mounted successfully

Launching web server...
Creating Web MicroServices...
WiFi Mode: 0
Scanned 16 Networks...
 0: LA-Guest (-38dBm) CH:6 MAC:7E:45:58:XX:XX:XX
 1: LA-2G (-38dBm) CH:6 MAC:82:45:58:XX:XX:XX
 2: LA (-39dBm) CH:6 MAC:78:45:58:XX:XX:XX
 3: LA-2G-AUX (-63dBm) CH:1 MAC:DC:A6:32:XX:XX:XX
 4: MOVISTAR_EC40 (-68dBm) CH:1 MAC:88:DE:7C:XX:XX:XX
 5: NoltariA32 (-70dBm) CH:6 MAC:82:5F:04:XX:XX:XX
 6: MIWIFI_kvTK (-76dBm) CH:1 MAC:1C:64:99:XX:XX:XX
 7: sercommBA2385 (-79dBm) CH:13 MAC:48:3E:5E:XX:XX:XX
 8: LA (-82dBm) CH:11 MAC:78:45:58:XX:XX:XX
 9: LA-2G (-82dBm) CH:11 MAC:82:45:58:XX:XX:XX
 10: LA-Guest (-82dBm) CH:11 MAC:7E:45:58:XX:XX:XX
 11: MOVISTAR_0599 (-83dBm) CH:6 MAC:E4:AB:89:XX:XX:XX
*12:  (-83dBm) CH:6 MAC:02:71:47:XX:XX:XX
 13: MAGODEOZ (-88dBm) CH:7 MAC:94:28:6F:XX:XX:XX
 14: WEDU_PROF (-91dBm) CH:1 MAC:F0:3F:95:XX:XX:XX
 15: WEDU_CM (-93dBm) CH:1 MAC:F0:3F:95:XX:XX:XX

Turning the HotSpot On
Initializing AP for credentials modification

SoftAP IP: 192.168.4.1
......................1111111Loading file index.js
1Socket [0] Connected from 192.168.4.2 url: /
Setting Transceiver Json
Serialize Radio JSON SCK:18 MISO:19 MOSI:23 CSN:5 RX:13 TX:12
1Client 0 joining room 0
1Client 0 leaving room 0
111111111111111111111111
```

**Comment by rstrouse** [comment]
Yeah the C3 chips using the RISC-V do not compile with the standard math libraries.  It is very odd that nobody appears to do floating point math with that chip.  The other thing that seemed to be different are the hardware interrupts but that could simply be differences in the IRAM interface.

Is this including the file system in the onboard?

**Comment by Noltari** [comment]
> Yeah the C3 chips using the RISC-V do not compile with the standard math libraries. It is very odd that nobody appears to do floating point math with that chip. The other thing that seemed to be different are the hardware interrupts but that could simply be differences in the IRAM interface.
> 
> Is this including the file system in the onboard?

Yes, it's included: https://github.com/Noltari/ESPSomfy-RTS/blob/eb2abb6994b4d68d9c29d95de5e4c5e50e967654/.github/workflows/ci.yaml#L123

**Comment by rstrouse** [comment]
I merged the pull and also added some bits for the awning integration.

**Pull request merged**
